/* Episode 5: Ten Thousand Steps — Puchi walks. Chika "delegates" her steps to Pyoko the bunny. */
const steps = (n, done) => t => winPill('Steps', t, PILL_Y, 0, done ? n + ' ✓' : n);
const BENCH = 105, pyoko = o => Object.assign({char: 'bunny', x: 70, look: -1}, o);
episode({id: 'a05-steps', shots: [
  shot({name: 'crawl', set: 'park', cam: 'cu:p', in: 'black', hud: true, card: steps('9,999'),
    p: t => ({lift: -2, eyes: 'spiral', mouth: 'wobble', fx: ['sweat2'], shake: Math.floor(t * 4) % 2, bob: false}), sfx: [[.2, 'step'], [1.4, 'step']],
    lines: [['p', 'Just... one... more...', 'あと… いっぽ…', 'tired', {say: 'あと…いっぽ…'}]]}),
  shot({name: 'already', set: 'park', cam: rel([[0, BENCH, 58, 44], [1, BENCH, 59, 40]]), hud: true, card: steps('10,000', true),
    c: {x: BENCH, lift: 5, eyes: 'half', mouth: 'cat', look: -1, bob: false}, props: [['phone', BENCH + 9, 62, C.BLUE]], sfx: [[0, 'ding2']],
    lines: [['c', 'Already done.', 'もう おわった。', 'smug']]}),
  titleShot(5, 'いちまんぽ', 'Ten Thousand Steps'),
  timeCard('けさ', 'THIS MORNING'),
  shot({name: 'plan', set: 'park', cam: 'two', music: 'field', hud: true, card: steps('0'), p: {eyes: 'shine', mouth: 'open', arms: 'up', cheeks: true}, c: {eyes: 'half', mouth: 'flat'},
    lines: [['p', 'Today: ten thousand steps!', 'きょうは いちまんぽ！', 'excited', {say: 'きょうは、いちまんぽ！'}],
            ['c', 'Ten thousand. Got it.', 'いちまん。りょうかい。', 'deadpan']]}),
  shot({name: 'jog 1', style: 'speed', cam: rel([[0, PX, 60, 46, .07], [1, PX, 60, 42, .09]]), dur: 1.2, hud: true, card: steps('1,240'),
    p: t => ({eyes: 'squeeze', mouth: 'open', arms: Math.floor(t * 6) % 2 ? 'up' : 'down', hop: [0, .25, 2, true]}), sfx: [[.05, 'step'], [.3, 'step'], [.55, 'step'], [.8, 'step']]}),
  shot({name: 'jog 2', style: 'speed', cam: rel([[0, PX, 60, 46, -.07], [1, PX, 60, 42, -.09]]), dur: 1.2, hud: true, card: steps('4,870'),
    p: t => ({eyes: 'squeeze', mouth: 'wobble', fx: ['sweat2'], arms: Math.floor(t * 6) % 2 ? 'up' : 'down', hop: [0, .25, 2, true]}), sfx: [[.05, 'step'], [.3, 'step'], [.55, 'step'], [.8, 'step']]}),
  shot({name: 'bench', set: 'park', cam: rel([[0, 92, 58, 60], [1, 92, 59, 54]]), music: 'stop',
    c: {x: BENCH, lift: 5, eyes: 'half', mouth: 'flat', look: -1, bob: false}, friends: [t => pyoko({x: Math.round(lerp(60, 82, clamp(t / 1, 0, 1))), hop: [0, .35, 2, true]})],
    props: [['phone', BENCH + 9, 62, C.BLUE]], sfx: [[.1, 'boing'], [.45, 'boing'], [.8, 'boing']],
    lines: [['c', 'Pyoko. Want a snack?', 'ピョコ、おやつ ほしい？', 'smug', {at: 1.0, say: 'ピョコ、おやつ、ほしい？'}]]}),
  attackShot('c', '秘技・うさぎだいこう', 'SECRET ART: BUNNY DELEGATION', 'ひぎっ！うさぎ、だいこう！', {music: {track: 'battle', vol: .6}}),
  shot({name: 'pyoko runs', style: 'speed', cam: rel([[0, 70, 60, 48], [1, 70, 60, 44]]), dur: 2.4, hud: true,
    card: t => steps(t < .7 ? '6,000' : t < 1.4 ? '9,000' : '10,000', t >= 1.4)(t), friends: [t => pyoko({x: 70, hop: [0, .2, 4, true], eyes: 'happy', mouth: 'open'})],
    front: t => art2('phone', 75, 60 - Math.round(4 * Math.abs(Math.sin(t * 15.7))), C.BLUE), sfx: [[0, 'boing'], [.4, 'boing'], [.8, 'boing'], [1.2, 'boing'], [1.4, 'win']]}),
  shot({name: 'leadership?', set: 'park', cam: 'cu:p', music: 'stop', hud: true, card: steps('9,999'), p: t => ({lift: -2, eyes: 'tired', mouth: 'wobble', fx: ['sweat2', 'gloom'], bob: false}),
    lines: [['p', 'Chika... you didn’t walk... at all...', 'チカ… ぜんぜん あるいてない…', 'tired', {say: 'チカ…ぜんぜん、あるいてない…'}]]}),
  shot({name: 'leadership', style: 'gold', cam: 'cu:c', c: {eyes: 'half', mouth: 'cat', arms: 'wave'}, sfx: [[0, 'shine']],
    lines: [['c', 'I walked to the bench. That’s leadership.', 'ベンチまで あるいた。リーダーシップ。', 'smug', {say: 'ベンチまで、あるいた。リーダーシップ。'}]]}),
  shot({name: 'even pyoko', set: 'park', cam: 'two', p: {eyes: 'dot', mouth: 'scream', arms: 'up', fx: ['shock'], shake: 1, bob: false}, c: false,
    friends: [pyoko({x: 78, hop: [0, .3, 2, true], eyes: 'happy'})], shake: [[0, .3, 18]], sfx: [[0, 'gasp']],
    lines: [['p', 'Even PYOKO has more steps than me!', 'ピョコのほうが おおい！', 'shout', {style: 'shout', pos: [540, 420], tail: false, say: 'ピョコのほうが、おおいじゃん！'}]]}),
  shot({name: 'last step', set: 'park', cam: 'cu:p', music: 'town', hud: true, card: t => steps(t < .5 ? '9,999' : '10,000', t >= .5)(t), win: [.5, 'Walked 10,000 steps'],
    p: t => ({lift: t < .5 ? 2 : -2, eyes: 'cry', mouth: 'open', bob: false}), sfx: [[.5, 'thud'], [.55, 'fanfare']],
    lines: [['p', 'I... did it...', 'やった…', 'tired', {at: 1.0, say: 'やった…やったよ…'}]]}),
  shot({name: 'teamwork', set: 'park', cam: 'two', p: {lift: -2, eyes: 'happy', mouth: 'smile'}, c: {eyes: 'half', mouth: 'cat', arms: 'up'},
    friends: [pyoko({x: 66, eyes: 'happy', hop: [0, .3, 2, true]})], props: [['apple', 68, 60, C.RED]],
    lines: [['c', 'Teamwork. Everyone wins.', 'チームワーク。みんな かち。', 'smug', {say: 'チームワーク。みんな、かち。'}]]}),
  tsuzukuShot('Zen Master Chika')
]});
