/* Episode 7: The Piggy Bank — Puchi saves coin by coin. Chika "saves 70%" at a sale. */
const bags = (x, n) => () => { for(let i = 0; i < n; i++) art2('bag', x + (i % 3) * 6 - 6, 70 - Math.floor(i / 3) * 5, [C.PINK, C.MINT, C.GOLD, C.LILAC, C.BLUE][i % 5]); };
const GOLDEVIL = t => { letterbox(1, 150); const a = clamp((t - .2) / .3, 0, 1); [[170, 520, -.2], [880, 600, .18]].forEach(([x, y, r]) => mangaSfx('ゴ', x, y + Math.sin(t * 3) * 15, {size: 140, fill: '#b48cff', stroke: '#120a1f', alpha: a, rot: r})); };
episode({id: 'a07-piggy', shots: [
  shot({name: 'bags', set: 'living', cam: 'two', in: 'black', p: {eyes: 'dot', mouth: 'o', fx: ['sweat']}, c: t => ({eyes: 'happy', mouth: 'cat', arms: 'up', walk: [104, 80, 0, .8]}),
    front: t => bags(Math.round(lerp(104, 80, clamp(t / .8, 0, 1))) + 4, 9)(), sfx: [[.1, 'step'], [.3, 'step'], [.5, 'step'], [.9, 'pile']],
    lines: [['c', 'I saved SO much money today.', 'きょう すごく せつやく した。', 'smug', {at: 1.0, say: 'きょう、すっごく、せつやくした。'}]]}),
  shot({name: 'saved?', style: 'shock', cam: 'snap:p', shake: [[0, .4, 20]], p: {eyes: 'dot', mouth: 'scream', arms: 'up', fx: ['shock'], shake: 1, bob: false},
    over: OVER.gaan(820, 1180), sfx: [[0, 'thunder']],
    lines: [['p', 'With NINE shopping bags?!', 'ふくろ きゅうこで？！', 'shout', {style: 'shout', pos: [540, 420], tail: false, say: 'ふくろ、きゅうこで？！'}]]}),
  titleShot(7, 'ちょきん ばこ', 'The Piggy Bank'),
  timeCard('けさ', 'THIS MORNING'),
  shot({name: 'coins', set: 'living', cam: 'two', music: 'town', hud: true, card: t => winPill('Savings', t, PILL_Y, 0, t < 1.4 ? '¥100' : '¥200'),
    p: t => ({eyes: 'happy', mouth: 'open', cheeks: true, arms: Math.floor(t * 2) % 2 ? 'wave' : 'down'}), c: {eyes: 'half', mouth: 'flat'},
    props: [['piggy', 56, 66, C.PINK], t => (t % 1.4) < .5 ? ['coin', 58, 58 + Math.floor((t % 1.4) * 14), C.GOLD] : null], sfx: [[.4, 'coin'], [1.8, 'coin']],
    lines: [['p', 'One coin a day. Slow and steady!', 'まいにち いちまい。こつこつ！', 'excited', {at: .5, say: 'まいにち、いちまい。こつこつ！'}],
            ['c', 'One coin. Wow. Thrilling.', 'いちまい。わあ。すごい。', 'deadpan']]}),
  shot({name: 'sale', set: 'street', cam: 'ms:c', music: 'stop', c: {eyes: 'shine', mouth: 'open', arms: 'up'},
    over: t => { const k = Math.floor(t * 6) % 2; otext('70% OFF', 540, 1180, {font: 'Dot', w: 400, size: 90, fill: k ? '#ffd36b' : '#fff', stroke: '#e8455f', sw: 14, rot: .08}); },
    sfx: [[0, 'ding2'], [.2, 'sparkle']], lines: [['c', 'Seventy percent... off?', 'ななじゅっパーセント… オフ？', 'excited', {at: .5, say: 'ななじゅっパーセント…オフ？'}]]}),
  attackShot('c', '秘技・セールがり', 'SECRET ART: SALE HUNT', 'ひぎっ！セール、がり！', {music: {track: 'battle', vol: .6}}),
  shot({name: 'shopping', style: 'speed', cam: rel([[0, CX, 60, 46, .08], [1, CX, 60, 42, .1]]), dur: 1.6, c: t => ({eyes: 'evil', mouth: 'grin', arms: Math.floor(t * 8) % 2 ? 'up' : 'wave', shake: 1}),
    front: t => bags(CX + 4, Math.min(9, 1 + Math.floor(t * 6)))(), sfx: [[0, 'coin'], [.25, 'coin'], [.5, 'coin'], [.75, 'coin'], [1, 'coin'], [1.25, 'coin']]}),
  timeCard('そして いま', 'AND NOW', {ff: true}),
  shot({name: 'math', style: 'gold', cam: 'cu:c', music: {track: 'battle', vol: .55}, c: {eyes: 'half', mouth: 'cat', arms: 'wave'}, win: [1.4, 'Saved 70%'], sfx: [[0, 'shine']],
    lines: [['c', 'Every bag saved me seventy percent. Math.', 'ぜんぶ ななじゅっパーセント せつやく。さんすう。', 'smug', {say: 'ぜんぶ、ななじゅっパーセント、せつやく。さんすう。'}]]}),
  shot({name: 'spent', set: 'living', cam: 'cu:p', p: {eyes: 'squeeze', mouth: 'scream', fx: ['vein'], arms: 'up', shake: 1},
    lines: [['p', 'You didn’t SAVE money! You SPENT it!', 'せつやく じゃない！つかったの！', 'shout', {say: 'せつやくじゃない！つかったんだよ！'}]]}),
  shot({name: '700', style: 'evil', cam: 'low:c', music: 'stop', c: {eyes: 'evil', mouth: 'grin', arms: 'up', bob: false}, over: GOLDEVIL, sfx: [[0, 'menace']],
    lines: [['c', 'So if I buy TEN... I save seven hundred percent.', 'じゅっこ かえば… ななひゃくパーセント せつやく。', 'smug', {pos: [540, 420], tail: false, say: 'じゅっこ、かえば…ななひゃくパーセント、せつやく。'}]]}),
  shot({name: 'brain', style: 'shock', cam: 'ecu:p', p: t => ({eyes: 'spiral', mouth: 'wobble', fx: ['sweat2'], sway: Math.floor(t * 4) % 2, bob: false}),
    over: t => { const a = t * 3; [0, 1, 2, 3].forEach(i => otext(['%', '¥', '?', '7'][i], 540 + Math.cos(a + i * 1.57) * 330, 820 + Math.sin(a + i * 1.57) * 120, {font: 'Dot', w: 400, size: 90, fill: '#ffd36b', stroke: '#1b1d4a', sw: 12})); },
    sfx: [[0, 'boing']], lines: [['p', '...My brain is loading...', '…あたまが… ローディング…', 'tired', {at: .6, say: 'あたまが…ろーでぃんぐ…'}]]}),
  shot({name: 'invest', set: 'living', cam: 'two', music: 'town', p: {eyes: 'dot', mouth: 'o'}, c: t => ({eyes: 'happy', mouth: 'cat', walk: [80, 62, 0, .6]}),
    props: [t => ['piggy', t < .7 ? 56 : 66, t < .7 ? 66 : 58 + (Math.floor(t * 12) % 2), C.PINK]], sfx: [[.8, 'rattle', 1]],
    lines: [['c', 'Can I borrow the piggy? It’s an investment.', 'ぶたさん かして。とうし だから。', 'smug', {at: .9, say: 'ぶたさん、かして。とうし、だから。'}],
            ['p', 'NO!!', 'だめ！！', 'shout', {style: 'shout', say: 'だめーっ！'}]]}),
  tsuzukuShot('Gym Day')
]});
