/* generated by pack.py from src/engine.js: do not edit */
/* ---------- pixel pet engine: a 64×36 colour screen and the Puchis drawn on it ---------- */
let LW = 128, LH = 100, G = 76;
// a pixel is 0 (off), 1 (the crayon's dark line), 2 (its middle tone), 3 (its pale fill) or 4 (a soft
// in-between tone for scenery far behind).
// Each pixel also remembers the crayon (PEN) it was drawn with.
const buf = new Uint8Array(LW*LH), cbuf = new Uint8Array(LW*LH);
let PEN = 0;
// NIGHT is Chika's dark body; MOON is a light ink for faces drawn on a dark body (white line, lavender middle, a dark "pale" that becomes the pupil)
const C = {INK:0, PET:1, LEAF:2, RED:3, GOLD:4, LILAC:5, BLUE:6, BROWN:7, ORANGE:8, MINT:9, GRAY:10, PINK:11, NIGHT:12, MOON:13};
const P = (x,y,v) => { x |= 0; y |= 0; if(x < 0 || y < 0 || x >= LW || y >= LH) return; const i = y*LW+x; buf[i] = v == null ? 1 : v; cbuf[i] = PEN; };
const GET = (x,y) => (x < 0 || y < 0 || x >= LW || y >= LH) ? -1 : buf[y*LW+x];
function clearLCD(){ buf.fill(0); cbuf.fill(0); PEN = 0; }
// pens: one crayon per row (the last one carries on), for sprites with a stem, a roof…
function spr(rows, x0, y0, dark, pens){
  const keep = PEN;
  for(let j = 0; j < rows.length; j++){ const r = rows[j];
    if(pens) PEN = pens[Math.min(j, pens.length - 1)];
    for(let i = 0; i < r.length; i++){ const ch = r[i];
      if(ch === 'X') P(x0+i, y0+j, dark == null ? 1 : dark); else if(ch === 'o') P(x0+i, y0+j, 2); else if(ch === '_') P(x0+i, y0+j, 0); } }
  PEN = keep;
}
const withPen = (c, fn) => { const keep = PEN; PEN = c; fn(); PEN = keep; };
function blob(cx, cy, rx, ry, fill){
  const ins = (x,y) => { const dx = (x+.5-cx)/rx, dy = (y+.5-cy)/ry; return dx*dx + dy*dy <= 1; };
  const x0 = Math.floor(cx-rx)-1, x1 = Math.ceil(cx+rx)+1, y0 = Math.floor(cy-ry)-1, y1 = Math.ceil(cy+ry)+1;
  for(let y = y0; y <= y1; y++) for(let x = x0; x <= x1; x++){
    if(!ins(x,y)) continue;
    if(!ins(x-1,y) || !ins(x+1,y) || !ins(x,y-1) || !ins(x,y+1)){ P(x,y,1); continue; }
    const dx = (x+.5-cx)/rx, dy = (y+.5-cy)/ry;
    P(x, y, (dx*.35 + dy > .62 && ((x+y)&1)) ? 2 : (fill || 3));
  }
  return ins;
}
const SHAPES = [{rx:5,ry:6},{rx:5.5,ry:4.5},{rx:7,ry:5.5},{rx:8,ry:6.5},{rx:9,ry:7},{rx:10,ry:7.5},{rx:10.5,ry:8}];
const EX = [0,2,3,3,4,4,4];
const PLANTS = {
  1:{sc:2, head:0, rows:['XX.XX','.XXX.','..X..','..X..']},
  2:{sc:3, head:0, rows:['XX...XX','XXX.XXX','.XX.XX.','..XXX..','...X...','...X...']},
  3:{sc:3, head:4, rows:['...X...','..XoX..','..XoX..','...X...','XX.X.XX','.XXXXX.','...X...','...X...']},
  4:{sc:3, head:7, rows:['..XXX..','..X.X..','XXXoXXX','X.oXo.X','XXXoXXX','..X.X..','..XXX..','...X...','XX.X.XX','.XXXXX.','...X...']},
  5:{sc:3, head:7, rows:['..XXX..','..XoX..','XXXoXXX','XooXooX','XXXoXXX','..XoX..','..XXX..','...X...','XX.X.XX','.XXXXX.','...X...']}
};
PLANTS[6] = PLANTS[5];
const HEART = ['.X.X.','XXXXX','XXXXX','.XXX.','..X..'];
const HEART_S = ['X.X','XXX','.X.'];
const SPARK = ['.X.','XXX','.X.'];
const ZZ = ['XXX','..X','.X.','XXX'];
const SUN_A = ['...X...','.......','..XXX..','X.XXX.X','..XXX..','.......','...X...'];
const SUN_B = ['.......','.X...X.','..XXX..','..XXX..','..XXX..','.X...X.','.......'];
const MOON = ['.XX..','XX...','X....','XX...','.XX..'];
const FLOWER_F = ['.X.','XoX','.X.','.X.'];
const FLOWER_B = ['.X.','X.X','.X.','.o.','.o.','.o.'];
const FRONT = [1,60,5,56,9,52,13,48];
const BACK = [3,58,7,54,11,50];

const Pet = {
  F:0, stage:0, x:0, tx:0, facing:1, nextWalk:30, nextBlink:20, blinkUntil:0, anim:null, evo:null, grow:null, parts:[], seenStage:null,
  syncStage(){ const s = stageOf(totalXp()); if(!this.evo) this.stage = s; },
  react(type){ this.anim = {type, f0:this.F}; },
  evolve(from, to){ this.evo = {from, to, f0:this.F}; this.stage = to; this.anim = null; },
  spawn(kind, x, y){ this.parts.push({kind, x, y, life: kind === 'spark' ? 6 : 22}); }
};

// the plant on the head of Puchi (a pink flower) and of Chika (a white moon flower); flower and leaf are crayons
function drawPlant(stage, cx, top, sway, flower, leaf){
  const p = PLANTS[stage]; if(!p) return;
  const h = p.rows.length; const x0 = cx - 1 - p.sc; const y0 = top - h;
  for(let j = 0; j < h; j++){ PEN = j < p.head ? (flower == null ? C.PINK : flower) : (leaf == null ? C.LEAF : leaf); spr([p.rows[j]], x0 + (j < p.head ? sway : 0), y0 + j); }
  PEN = C.PET;
}
function drawSeed(cx, cy, st, ch){
  const sh = SHAPES[0]; PEN = ch.egg; blob(cx, cy, sh.rx, sh.ry);
  const c = Math.round(cy);
  [[-3,-2],[1,-4],[2,1],[-2,2],[-1,-3]].forEach(p => { const x = cx+p[0], y = c+p[1]; if(GET(x,y) !== 1) P(x,y,2); if(GET(x+1,y) !== 1) P(x+1,y,2); });
  const xp = totalXp();
  // the seed sprouts a leaf; the eggs get a crack
  PEN = ch.plant ? ch.leaf : (ch.ink || C.INK);
  if(xp >= 1) (ch.plant ? [[-4,0],[-3,-1],[-2,0],[-1,-1],[0,0]] : [[-4,-1],[-3,0],[-2,-1],[-1,0],[0,-1]]).forEach(p => P(cx+p[0], c+p[1]));
  PEN = ch.ink || C.INK;
  if(xp >= 2){ [[1,-1],[2,0],[3,-1]].forEach(p => P(cx+p[0], c+p[1])); if(!st.blink){ P(cx-2, c+2); P(cx+1, c+2); } }
}
/* ---------- characters ----------
   Every Puchi grows through the same seven stages and moves the same way; what changes is its colour,
   what grows on its head, and a few extras (whiskers and a tail, a beak). Stage 0 is a seed for the
   Sprout and an egg for the others. */
// the top edge of the body at column x (first row inside the blob, from above)
function edgeY(ins, x, from){ for(let y = Math.max(0, from - 12); y < LH; y++) if(ins(x, y)) return y; return from; }
function drawBunnyEars(stage, cx, top, sway, ins){
  const len = [0, 2, 3, 5, 6, 7, 7][stage], gap = stage >= 4 ? 2 : 1;
  [cx - 2 - gap, cx + gap - 1].forEach((x0, side) => {
    const base = edgeY(ins, x0 + 1, top);
    for(let j = 1; j <= len; j++){
      const y = base - j, tip = j === len, lean = (sway && side === 0 && j > len - 2) ? -1 : 0;
      PEN = CHARS.bunny.pen;
      if(tip){ P(x0 + 1 + lean, y); continue; }
      P(x0 + lean, y); P(x0 + 2 + lean, y);
      PEN = C.PINK; P(x0 + 1 + lean, y, j < len - 1 ? 2 : 3);
    }
  });
  if(stage >= 6){ PEN = C.GOLD; P(cx + gap + 2, top - len + 1); P(cx + gap + 3, top - len, 2); }
}
function drawCatEars(stage, cx, top, sway, ins){
  const h = [0, 2, 2, 3, 3, 3, 4][stage], off = Math.max(2, Math.round(SHAPES[stage].rx * .55));
  [cx - off - 1, cx + off].forEach(xc => {
    const base = edgeY(ins, xc, top);
    for(let j = 1; j <= h; j++){
      const w = h - j;   // half-width of this row of the triangle
      PEN = CHARS.kitty.pen;
      if(w === 0){ P(xc, base - j); continue; }
      P(xc - w, base - j); P(xc + w, base - j);
      PEN = C.PINK; for(let x = xc - w + 1; x < xc + w; x++) P(x, base - j, 2);
    }
  });
}
function drawStripes(stage, cx, top, ins){
  if(stage < 2) return;
  PEN = CHARS.kitty.pen;
  [cx - 3, cx - 1, cx + 2].forEach((x, i) => { const n = i === 1 ? 2 : 1; for(let j = 1; j <= n; j++) if(ins(x, top + j) && GET(x, top + j) !== 1) P(x, top + j, 2); });
}
function drawTail(stage, cx, cy, sh, bottom){
  if(stage < 2) return;
  PEN = CHARS.kitty.pen;
  const x = Math.round(cx + sh.rx) - 2, y = bottom;
  [[0, 0, 1], [1, 0, 1], [2, 0, 2], [3, -1, 1], [4, -2, 2], [4, -3, 1], [3, -4, 1]].slice(0, stage >= 4 ? 7 : 5).forEach(p => P(x + p[0], y + p[1], p[2]));
}
function drawTuft(stage, cx, top){
  if(stage >= 5){ PEN = C.RED; spr(['X.X.X', 'XXXXX'], cx - 3, top - 2); return; }
  PEN = C.ORANGE;
  if(stage >= 1) P(cx - 1, top - 1);
  if(stage >= 2){ P(cx - 2, top - 2); P(cx, top - 2, 2); }
  if(stage >= 3){ P(cx - 1, top - 3); P(cx + 1, top - 1, 2); }
}
function drawBeak(m, my, mouth, big){
  PEN = C.ORANGE;
  if(mouth === 'open'){ P(m - 1, my); P(m, my); P(m - 1, my + 2); P(m, my + 2); if(big){ P(m - 1, my + 1, 3); P(m, my + 1, 3); } }
  else if(mouth === 'sleep'){ P(m - 1, my, 2); P(m, my, 2); }
  else { P(m - 1, my); P(m, my); P(m - 1, my + 1, 2); P(m, my + 1, 2); }
  PEN = C.INK;
}
function drawBearEars(stage, cx, top, sway, ins){
  const big = stage >= 3, off = Math.max(2, Math.round(SHAPES[stage].rx * .6));
  [cx - off - 1, cx + off].forEach(xc => {
    const base = edgeY(ins, xc, top);
    PEN = CHARS.bear.pen;
    if(!big){ P(xc - 1, base - 1); P(xc + 2, base - 1); P(xc, base - 2); P(xc + 1, base - 2); P(xc, base - 1, 4); P(xc + 1, base - 1, 4); return; }
    P(xc - 2, base - 1); P(xc + 2, base - 1); P(xc - 1, base - 2); P(xc, base - 2); P(xc + 1, base - 2);
    P(xc - 1, base - 1, 4); P(xc + 1, base - 1, 4); PEN = C.PINK; P(xc, base - 1, 2);
  });
  if(stage === 5){ PEN = C.LEAF; spr(['.XX', 'XX.', '.X.'], cx - 2, top - 3); }   // a leaf from the forest
  if(stage >= 6){ PEN = C.GOLD; spr(['X.X.X', 'XXXXX'], cx - 3, top - 2); }
}
// a creamy muzzle and a button nose
function drawMuzzle(stage, cx, top, ins, my, big, L){
  const m = cx + (L || 0), w = big ? 3 : 2;
  PEN = CHARS.bear.pen;
  for(let y = my - 1; y <= my + (big ? 2 : 1); y++) for(let x = m - w; x < m + w; x++){
    const corner = (x === m - w || x === m + w - 1) && (y === my - 1 || y === my + (big ? 2 : 1));
    if(!corner && ins(x, y) && GET(x, y) !== 1) P(x, y, 3);
  }
  if(big){ PEN = C.INK; P(m - 1, my - 1); P(m, my - 1); }
}
function drawFrogBumps(stage, cx, top, sway, ins){
  const big = stage >= 3, ex = EX[stage];
  PEN = CHARS.frog.pen;
  [-1, 1].forEach(side => {
    // a dome over each eye, its walls running down until they meet the body
    const x0 = big ? (side < 0 ? cx - 4 - ex : cx + ex - 2) : (side < 0 ? cx - 2 - ex : cx + ex - 1), w = big ? 6 : 3;
    const y0 = big ? top - 3 : top - 2, x1 = x0 + w - 1;
    let base = y0; for(let x = x0; x <= x1; x++) base = Math.max(base, edgeY(ins, x, top));
    for(let y = y0; y <= base; y++) for(let x = x0; x <= x1; x++){
      const wall = x === x0 || x === x1, roof = y === y0;
      if(roof && wall) continue;
      if(GET(x, y) === 1 && !wall && !roof) { P(x, y, 4); continue; }
      if(wall || roof) { if(!(ins(x, y) && GET(x, y) !== 1 && !roof && y > top)) P(x, y, 1); }
      else P(x, y, 4);
    }
  });
  if(stage >= 4){ PEN = C.PINK; spr(['.X.', 'XoX', '.X.'], cx - 2, top - 3); }
  if(stage >= 6){ PEN = C.GOLD; spr(['X.X', 'XXX'], cx - 2, top - 5); }
}
// a wide froggy grin
function frogMouth(stage, m, my, mouth, big){
  PEN = C.INK;
  if(mouth === 'smile'){ P(m - 3, my - 1); P(m + 2, my - 1); }
  else if(mouth === 'neutral' || mouth == null){ P(m - 2, my + 1); P(m + 1, my + 1); P(m - 3, my); P(m + 2, my); }
}
const CHARS = {
  // Puchi and Chika: the two first friends, light and dark, both open from the start
  sprout: {id: 'sprout', xp: 0, pen: C.PET, egg: C.BROWN, plant: true, leaf: C.LEAF, head: (s, cx, top, sway) => drawPlant(s, cx, top, sway, C.PINK, C.LEAF)},
  chika: {id: 'chika', xp: 0, pen: C.NIGHT, egg: C.NIGHT, ink: C.MOON, plant: true, leaf: C.MINT, head: (s, cx, top, sway) => drawPlant(s, cx, top, sway, C.GOLD, C.MINT)},
  bunny: {id: 'bunny', xp: 30, pen: C.LILAC, egg: C.LILAC, head: drawBunnyEars},
  kitty: {id: 'kitty', xp: 75, pen: C.ORANGE, egg: C.ORANGE, head: drawCatEars, face: (s, cx, top, ins) => drawStripes(s, cx, top, ins), back: drawTail},
  chick: {id: 'chick', xp: 140, pen: C.GOLD, egg: C.GOLD, feet: C.ORANGE, head: drawTuft, beak: true},
  // sold in the store (pack: the bundle they come in; never opened by wins)
  bear: {id: 'bear', xp: Infinity, pack: 'char-bear', pen: C.BROWN, egg: C.BROWN, fill: 4, head: drawBearEars, face: drawMuzzle},
  frog: {id: 'frog', xp: Infinity, pack: 'char-frog', pen: C.LEAF, egg: C.MINT, fill: 4, head: drawFrogBumps, eyesUp: true, after: frogMouth}
};
const CHAR_LIST = Object.keys(CHARS).map(k => CHARS[k]);
let CHAR = 'sprout';   // set by the page from the settings

function drawPet(stage, st){
  const ch = CHARS[st.char || CHAR] || CHARS.sprout;
  const sh = SHAPES[stage]; const cx = st.x != null ? st.x : 32 + st.xoff;
  const feet = stage >= 2;
  const bottom = (feet ? G-2 : G-1) - st.lift;
  const cy = bottom + 1 - sh.ry;
  const keepPen = PEN;
  if(stage === 0){ drawSeed(cx, cy, st, ch); PEN = keepPen; return {cx, top: Math.round(cy - sh.ry)}; }
  if(ch.back) ch.back(stage, cx, cy, sh, bottom);
  PEN = ch.pen;
  const ins = blob(cx, cy, sh.rx, sh.ry, ch.fill);
  let top = bottom; for(let y = bottom; y >= 0; y--){ if(ins(cx-1, y)) top = y; else break; }
  ch.head(stage, cx, top, st.sway, ins);
  const big = stage >= 3, ex = EX[stage], L = st.look;
  const faceY = Math.round(cy) - (big ? 2 : 1);
  const my = faceY + (big ? 4 : (stage === 1 ? 2 : 3));
  const eyeY = ch.eyesUp ? top - (big ? 2 : 1) : faceY;   // the frog's eyes sit up in their bumps
  PEN = C.PINK;
  if(st.cheeks){
    const xs = big ? [cx-ex-4, cx-ex-3, cx+ex+2, cx+ex+3] : [cx-ex-3, cx-ex-2, cx+ex+1, cx+ex+2];
    xs.forEach(x => { const xx = x + L; if(ins(xx, my-1) && GET(xx, my-1) !== 1) P(xx, my-1, 2); });
  }
  PEN = ch.ink || C.INK;   // the face: dark on the light friends, light on Chika
  if(st.eyes !== 'none') [-1, 1].forEach(side => {
    if(!big){
      const x = (side < 0 ? cx-1-ex : cx+ex) + L;
      if(st.eyes === 'open'){ P(x, eyeY); P(x, eyeY+1); }
      else if(st.eyes === 'blink'){ P(x, eyeY+1); }
      else if(st.eyes === 'happy'){ P(x-1, eyeY+1); P(x, eyeY); P(x+1, eyeY+1); }
      else { P(x-1, eyeY+1); P(x, eyeY+1); }
    } else {
      const a = (side < 0 ? cx-2-ex : cx+ex) + L, b = a+1;
      if(st.eyes === 'open'){ for(let y = eyeY; y < eyeY+3; y++){ P(a,y); P(b,y); } P(a, eyeY, 3); }
      else if(st.eyes === 'blink'){ P(a, eyeY+2); P(b, eyeY+2); }
      else if(st.eyes === 'happy'){ P(a-1, eyeY+1); P(a, eyeY); P(b, eyeY); P(b+1, eyeY+1); }
      else { P(a-1, eyeY+2); P(a, eyeY+2); P(b, eyeY+2); P(b+1, eyeY+2); }
    }
  });
  const m = cx + L;
  if(ch.face) ch.face(stage, cx, top, ins, my, big, L);
  if(st.mouth === 'none'){} else if(ch.beak){ drawBeak(m, my, st.mouth, big); }
  else if(st.mouth === 'smile'){ P(m-2,my); P(m+1,my); P(m-1,my+1); P(m,my+1); }
  else if(st.mouth === 'open'){
    for(let x = m-2; x <= m+1; x++) P(x, my);
    if(big){ P(m-2,my+1); P(m+1,my+1); P(m-1,my+1,2); P(m,my+1,2); P(m-1,my+2); P(m,my+2); }
    else { P(m-1,my+1); P(m,my+1); }
  }
  else if(st.mouth === 'sleep'){ P(m-1,my+1,2); P(m,my+1,2); }
  else if(st.mouth === 'sad'){ P(m-1,my); P(m,my); P(m-2,my+1); P(m+1,my+1); }
  else { P(m-1,my+1); P(m,my+1); }
  if(ch.after) ch.after(stage, m, my, st.mouth, big);
  // outfits bought with stars
  if(st.wear === 'glasses'){
    [-1, 1].forEach(side => {
      if(!big){ const x = (side < 0 ? cx-1-ex : cx+ex) + L; for(let i = -1; i <= 1; i++){ P(x+i, eyeY-1); P(x+i, eyeY+2); } P(x-1, eyeY); P(x-1, eyeY+1); P(x+1, eyeY); P(x+1, eyeY+1); }
      else { const a = (side < 0 ? cx-2-ex : cx+ex) + L; for(let i = -1; i <= 2; i++){ P(a+i, eyeY-1); P(a+i, eyeY+3); } for(let y = eyeY; y < eyeY+3; y++){ P(a-1, y); P(a+2, y); } }
    });
    const bl = cx - ex + L, br = cx + ex - (big ? 1 : 2) + L;
    for(let x = bl; x <= br; x++) P(x, eyeY);
  } else if(st.wear === 'scarf'){
    PEN = C.BLUE;
    const sy = my + (big ? 3 : 2);
    let xr = cx;
    for(let x = cx - 12; x <= cx + 12; x++){ if(ins(x, sy)){ P(x, sy); if(x > xr) xr = x; } if(ins(x, sy + 1)) P(x, sy + 1, (x & 1) ? 1 : 2); }
    P(xr - 2, sy + 2); P(xr - 1, sy + 2); P(xr - 2, sy + 3); P(xr - 1, sy + 3, 2); P(xr - 2, sy + 4, 2);
  } else if(st.wear === 'bow'){
    PEN = C.RED;
    const bx = cx + Math.round(sh.rx * .5) - 2, by = top - 1;
    spr(['XX.XX', 'XXXXX', 'XX.XX'], bx, by);
    P(bx + 2, by + 1, 2);
  }
  // the dress-up pack from the store
  else if(st.wear === 'crown'){
    PEN = C.GOLD;
    const w = big ? 7 : 5, x0 = cx - (w >> 1) - 1, y0 = top - 3;
    for(let i = 0; i < w; i++){ if(i % ((w - 1) >> 1) === 0) P(x0 + i, y0); P(x0 + i, y0 + 1, i % 2 ? 2 : 1); P(x0 + i, y0 + 2); }
    PEN = C.RED; P(x0 + (w >> 1), y0 + 1, 2);
  } else if(st.wear === 'flowers'){
    // a ring of little flowers along the top of the head
    const n = big ? 4 : 3, span = Math.round(sh.rx * 1.2), pens = [C.PINK, C.GOLD, C.LILAC, C.BLUE];
    for(let i = 0; i < n; i++){
      const x = Math.round(cx - 1 - span / 2 + i * span / (n - 1)), y = edgeY(ins, x, top) - 1;
      PEN = C.LEAF; if(i < n - 1) P(x + 1, y + 1, 2);
      PEN = pens[i % 4]; P(x - 1, y); P(x + 1, y); P(x, y - 1); P(x, y + 1); PEN = C.GOLD; P(x, y, 3);
    }
  } else if(st.wear === 'phones'){
    // headphones: a band over the head and a cup on each side
    const xl = Math.round(cx - sh.rx) - 1, xr = Math.round(cx + sh.rx) - 1;
    PEN = C.LILAC;
    for(let x = xl + 2; x <= xr - 2; x++) P(x, edgeY(ins, x, top) - 2, x === xl + 2 || x === xr - 2 ? 1 : 2);
    for(let y = edgeY(ins, xl + 2, top) - 1; y < faceY; y++){ P(xl + 1, y); P(xr - 1, y); }
    PEN = C.PINK;
    [xl, xr - 1].forEach(x => { for(let y = faceY; y < faceY + (big ? 4 : 3); y++){ P(x, y); P(x + 1, y, y === faceY || y === faceY + (big ? 3 : 2) ? 1 : 2); } });
  } else if(st.wear === 'shades'){
    // sunglasses: two dark lenses with a glint
    [-1, 1].forEach(side => {
      if(!big){ const x = (side < 0 ? cx-1-ex : cx+ex) + L; for(let y = eyeY; y <= eyeY + 1; y++) for(let i = -1; i <= 1; i++) P(x + i, y); PEN = C.GRAY; P(x - 1, eyeY, 3); PEN = C.INK; }
      else { const a = (side < 0 ? cx-2-ex : cx+ex) + L; for(let y = eyeY; y <= eyeY + 2; y++) for(let i = -1; i <= 2; i++) if(!(y === eyeY + 2 && (i === -1 || i === 2))) P(a + i, y); PEN = C.GRAY; P(a - 1, eyeY, 3); P(a, eyeY, 3); PEN = C.INK; }
    });
    const bl = cx - ex + L, br = cx + ex - (big ? 1 : 2) + L;
    for(let x = bl; x <= br; x++) P(x, eyeY);
  }
  PEN = ch.feet || ch.pen;
  if(feet){
    const fo = stage >= 3 ? 2 : 1; const fy = G - 1 - st.lift;
    P(cx-fo-2, fy - (st.step === 1 ? 1 : 0)); P(cx-fo-1, fy - (st.step === 1 ? 1 : 0));
    P(cx+fo, fy - (st.step === 2 ? 1 : 0)); P(cx+fo+1, fy - (st.step === 2 ? 1 : 0));
  }
  PEN = ch.pen;
  if(stage >= 3){
    const ay = Math.round(cy) + 1;
    let xl = cx - 1, xr = cx; while(ins(xl - 1, ay)) xl--; while(ins(xr + 1, ay)) xr++;
    const up = st.arms === 'up', waveR = st.arms === 'wave';
    if(up){ P(xl-1, ay-1); P(xl-2, ay-2); } else { P(xl-1, ay); P(xl-2, ay+1); }
    if(up || waveR){ P(xr+1, ay-1); P(xr+2, ay-2); } else { P(xr+1, ay); P(xr+2, ay+1); }
  }
  PEN = keepPen;
  return {cx, top, eyeY, my, ex, big, L, cy: Math.round(cy), bottom, rx: sh.rx};
}

function growRows(rows, i, F){
  if(!Pet.grow || Pet.grow.idx !== i) return rows;
  const a = F - Pet.grow.f0; if(a >= rows.length * 2){ return rows; }
  const n = Math.max(1, Math.ceil((a+1)/2)); return rows.slice(rows.length - n);
}


/* the screen: the 64×36 pixel buffer painted onto the canvas in a small, sweet palette
   (a dark line, a middle tone and a pale fill per crayon) */
const cv = document.getElementById('lcd'); const ctx = cv.getContext('2d');
const col = {inverted:false};
let SC = 4;
function paint(){ paintColor(ctx, cv.width, cv.height, SC); }

const PAL = [
  ['#3d2c4e', '#8f7fa3', '#efe8f5'],   // ink
  ['#cf5a7c', '#f29ab4', '#ffe1e9'],   // the pet
  ['#3b9656', '#7fcb8d', '#d5f2dc'],   // leaf
  ['#e8455f', '#f58aa0', '#ffd7df'],   // red
  ['#e3940c', '#f6c85a', '#fff0c2'],   // gold
  ['#7d62c9', '#b3a1ea', '#ebe5fb'],   // lilac
  ['#3b86d1', '#86bbee', '#dbecfd'],   // blue
  ['#94603a', '#c79770', '#f3e3d2'],   // brown
  ['#ec7232', '#f6a676', '#ffe4d3'],   // orange
  ['#1fa594', '#74d3c6', '#d2f4ef'],   // mint
  ['#767b8c', '#b1b4c1', '#eaebf0'],   // gray
  ['#e0609a', '#f39cc4', '#ffe0ee'],   // pink
  ['#17111f', '#2b2340', '#3e3459'],   // night: Chika's dark body
  ['#fffaff', '#d9cdef', '#2a2140']    // moon: a light face on a dark body
];
// the scenery tone: mostly the middle tone, a little towards the pale one
PAL.forEach(p => { const m = (a, b) => Math.round(parseInt(a, 16) * .62 + parseInt(b, 16) * .38).toString(16).padStart(2, '0'); p.push('#' + m(p[1].slice(1, 3), p[2].slice(1, 3)) + m(p[1].slice(3, 5), p[2].slice(3, 5)) + m(p[1].slice(5, 7), p[2].slice(5, 7))); });
// with the light off the screen glows in each crayon's middle tone; the dark ones glow in a light tone instead
PAL[C.NIGHT][4] = '#b9aae6'; PAL[C.MOON][4] = '#fffaff';
// on a dark place Chika's outline turns light, so she doesn't melt into the night
PAL[C.NIGHT][5] = '#9584cf';
// the backdrop behind the pixels: 'day', 'night' (sky over grass), 'sky', 'plain', or a background's
// colours {sky: [top, bottom], ground} (see scenes.js)
let SCENE = 'day';
function paintColor(ctx, W, Hh, s){
  const g = s >= 4 ? Math.max(1, Math.round(s * .14)) : 0; const q = s - g;
  const inv = col.inverted;
  ctx.globalAlpha = 1;
  if(inv){ ctx.fillStyle = '#26223f'; ctx.fillRect(0, 0, W, Hh); }
  else if(SCENE === 'plain'){ ctx.fillStyle = '#fff7ea'; ctx.fillRect(0, 0, W, Hh); }
  else {
    const o = typeof SCENE === 'object' ? SCENE : null, night = SCENE === 'night', gy = SCENE === 'sky' ? Hh : G * s;
    const sky = ctx.createLinearGradient(0, 0, 0, gy);
    sky.addColorStop(0, o ? o.sky[0] : night ? '#d4cdf2' : '#d6edff'); sky.addColorStop(1, o ? o.sky[1] : night ? '#f2edfb' : '#fff6e6');
    ctx.fillStyle = sky; ctx.fillRect(0, 0, W, gy);
    if(gy < Hh){ ctx.fillStyle = o ? o.ground : night ? '#d9ead4' : '#e1f4d2'; ctx.fillRect(0, gy, W, Hh - gy); }
  }
  ctx.fillStyle = inv || (SCENE && SCENE.dark) ? 'rgba(255,255,255,.04)' : 'rgba(61,44,78,.05)';
  for(let i = 0; i < buf.length; i++) if(buf[i] === 0) ctx.fillRect((i % LW) * s, ((i / LW) | 0) * s, q, q);
  let fs = '', ga = 1;
  const darkPlace = !inv && SCENE && SCENE.dark;
  for(let i = 0; i < buf.length; i++){
    const v = buf[i]; if(v === 0) continue;
    const p = PAL[cbuf[i]] || PAL[0];
    const c = inv ? (p[4] || p[1]) : (darkPlace && v === 1 && p[5]) ? p[5] : p[v === 1 ? 0 : v === 2 ? 1 : v === 4 ? 3 : 2];
    const a = inv ? (v === 1 ? .92 : v === 2 ? .4 : .12) : 1;
    if(c !== fs){ ctx.fillStyle = c; fs = c; }
    if(a !== ga){ ctx.globalAlpha = a; ga = a; }
    ctx.fillRect((i % LW) * s, ((i / LW) | 0) * s, q, q);
  }
  ctx.globalAlpha = 1;
}
