/* generated by pack.py from the app's Sound module: do not edit */
const Sound = (function(){
  const on = true; let lastPencil = 0;
  const comp = ac.createDynamicsCompressor(); comp.threshold.value = -20; comp.knee.value = 14; comp.ratio.value = 5; comp.attack.value = .003; comp.release.value = .18;
  const master = ac.createGain(); master.gain.value = .6; master.connect(comp); comp.connect(SFX_BUS);
  const len = Math.floor(ac.sampleRate * 1.1); const ir = ac.createBuffer(2, len, ac.sampleRate);
  for(let ch = 0; ch < 2; ch++){ const d = ir.getChannelData(ch); for(let i = 0; i < len; i++) d[i] = (Math.random()*2 - 1) * Math.pow(1 - i/len, 3.2); }
  const conv = ac.createConvolver(); conv.buffer = ir; const send = ac.createGain(); send.gain.value = .2; send.connect(conv); conv.connect(master);
  const noiseBuf = ac.createBuffer(1, ac.sampleRate, ac.sampleRate); const nd = noiseBuf.getChannelData(0); for(let i = 0; i < nd.length; i++) nd[i] = Math.random()*2 - 1;
  const ctx = () => ac; const pick = a => a[Math.floor(Math.random() * a.length)];
  const PENTA = [523.25,587.33,659.25,783.99,880,1046.5,1174.66,1318.51,1567.98,1760,2093];
  const jit = (v, p) => v * (1 + (Math.random()*2 - 1) * p);
  function out(node, wet){
    node.connect(master);
    if(wet !== 0){ const s = ac.createGain(); s.gain.value = wet == null ? 1 : wet; node.connect(s); s.connect(send); }
  }
  function tone(o){
    const c = ac;
    const t = NOW + .006 + (o.t || 0), a = o.a || .004, d = o.d || .12, vol = o.vol || .2;
    const osc = c.createOscillator(); osc.type = o.type || 'sine';
    osc.frequency.setValueAtTime(o.f, t);
    if(o.f1) osc.frequency.exponentialRampToValueAtTime(o.f1, t + (o.glide || d));
    if(o.vib){
      const l = c.createOscillator(), lg = c.createGain(); l.frequency.value = o.vib;
      lg.gain.setValueAtTime(o.f * .07, t); lg.gain.exponentialRampToValueAtTime(1, t + a + d);
      l.connect(lg); lg.connect(osc.frequency); l.start(t); l.stop(t + a + d + .05);
    }
    const g = c.createGain();
    g.gain.setValueAtTime(.0001, t); g.gain.exponentialRampToValueAtTime(vol, t + a); g.gain.exponentialRampToValueAtTime(.0001, t + a + d);
    let src = osc;
    if(o.lp){ const fl = c.createBiquadFilter(); fl.type = 'lowpass'; fl.frequency.value = o.lp; fl.Q.value = o.q || .7; osc.connect(fl); src = fl; }
    src.connect(g); out(g, o.wet);
    osc.start(t); osc.stop(t + a + d + .06);
  }
  function noise(o){
    const c = ac;
    const t = NOW + .006 + (o.t || 0), a = o.a || .001, d = o.d || .03, vol = o.vol || .1;
    const s = c.createBufferSource(); s.buffer = noiseBuf;
    const fl = c.createBiquadFilter(); fl.type = o.ft || 'bandpass'; fl.Q.value = o.q || 1;
    fl.frequency.setValueAtTime(o.f || 2500, t); if(o.f1) fl.frequency.exponentialRampToValueAtTime(o.f1, t + a + d);
    const g = c.createGain();
    g.gain.setValueAtTime(.0001, t); g.gain.exponentialRampToValueAtTime(vol, t + a); g.gain.exponentialRampToValueAtTime(.0001, t + a + d);
    s.loop = true;   // long breaths outlast the one-second noise sample
    s.connect(fl); fl.connect(g); out(g, o.wet);
    s.start(t, Math.random() * .5); s.stop(t + a + d + .05);
  }
  /* ---------- the music box ----------
     Tracks are written as one token per eighth note: a note (C5, F#4, Bb3), '-' to hold it, '.' for silence;
     drums use k (kick), s (snare), h (hi-hat). '|' only marks the bars. All tunes are Puchika originals. */
  const Music = (function(){
    const MKEY = 'puchika-music';
    let enabled = true; try { enabled = localStorage.getItem(MKEY) !== 'off'; } catch(e){}
    const NOTE = {C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11};
    const freq = n => { const m = /^([A-G])([#b]?)(\d)$/.exec(n); if(!m) return 0; const s = NOTE[m[1]] + (m[2] === '#' ? 1 : m[2] === 'b' ? -1 : 0) + (+m[3] + 1) * 12; return 440 * Math.pow(2, (s - 69) / 12); };
    function parse(str){
      const toks = str.replace(/\|/g, ' ').trim().split(/\s+/), ev = [];
      toks.forEach((t, i) => { if(t === '-'){ if(ev.length && ev[ev.length - 1].end === i) ev[ev.length - 1].end = i + 1; return; } if(t === '.') return; ev.push({at: i, end: i + 1, n: t}); });
      return {len: toks.length, ev};
    }
    const T = {
      title: {bpm: 96, lead: 'E5 - G5 - C6 - B5 A5 | G5 - - - D5 - G5 - | A5 - C6 - E6 - D6 C6 | A5 - - - F5 - A5 - | G5 - E5 - C5 - E5 G5 | B5 - A5 - G5 - D5 - | F5 - A5 - G5 - B5 - | C6 - - - - - . .',
        harm: 'C4 E4 G4 E4 C4 E4 G4 E4 | B3 D4 G4 D4 B3 D4 G4 D4 | A3 C4 E4 C4 A3 C4 E4 C4 | A3 C4 F4 C4 A3 C4 F4 C4 | C4 E4 G4 E4 C4 E4 G4 E4 | B3 D4 G4 D4 B3 D4 G4 D4 | A3 C4 F4 C4 B3 D4 G4 D4 | C4 E4 G4 E4 C4 - . .',
        bass: 'C3 - . . G2 - . . | G2 - . . D3 - . . | A2 - . . E3 - . . | F2 - . . C3 - . . | C3 - . . G2 - . . | G2 - . . D3 - . . | F2 - . . G2 - . . | C3 - - - . . . .'},
      town: {bpm: 88, lead: 'A4 - C5 - F5 - E5 C5 | D5 - - - Bb4 - D5 - | C5 - E5 - G5 - F5 E5 | F5 - - - C5 - . . | D5 - F5 - A5 - G5 F5 | Bb4 - D5 - F5 - D5 - | E5 - G5 - C5 - E5 G5 | F5 - - - - - . .',
        harm: '. A3 . C4 . A3 . C4 | . Bb3 . D4 . Bb3 . D4 | . G3 . C4 . G3 . E4 | . A3 . C4 . A3 . C4 | . F3 . A3 . F3 . A3 | . Bb3 . D4 . Bb3 . D4 | . G3 . C4 . G3 . Bb3 | . A3 . C4 . A3 . .',
        bass: 'F2 . C3 . F2 . C3 . | Bb2 . F3 . Bb2 . F3 . | C3 . G3 . C3 . G3 . | F2 . C3 . F2 . C3 . | D3 . A3 . D3 . A3 . | Bb2 . F3 . Bb2 . F3 . | C3 . G3 . C3 . E3 . | F2 . C3 . F2 - . .',
        drum: 'k . . h s . . h | k . . h s . . h | k . . h s . . h | k . . h s . h h | k . . h s . . h | k . . h s . . h | k . . h s . . h | k . . . s . . .'},
      field: {bpm: 126, lead: 'D5 - G5 - B5 - - A5 | G5 - E5 - B4 - - - | C5 - E5 - G5 - A5 G5 | F#5 - - - D5 - - - | D5 - G5 - B5 - D6 C6 | B5 - G5 - E5 - G5 - | A5 - G5 - F#5 - E5 F#5 | G5 - - - - - . .',
        harm: 'G3 B3 D4 B3 G3 B3 D4 B3 | E3 G3 B3 G3 E3 G3 B3 G3 | C4 E4 G4 E4 C4 E4 G4 E4 | D4 F#4 A4 F#4 D4 F#4 A4 F#4 | G3 B3 D4 B3 G3 B3 D4 B3 | E3 G3 B3 G3 E3 G3 B3 G3 | C4 E4 G4 E4 D4 F#4 A4 F#4 | G3 B3 D4 B3 G3 - . .',
        bass: 'G2 . G3 . G2 . G3 . | E2 . E3 . E2 . E3 . | C3 . C4 . C3 . C4 . | D3 . D4 . D3 . A2 . | G2 . G3 . G2 . G3 . | E2 . E3 . E2 . E3 . | C3 . C4 . D3 . D4 . | G2 . D3 . G2 - . .',
        drum: 'k . h . s . h h | k . h . s . h . | k . h . s . h h | k . h k s . h . | k . h . s . h h | k . h . s . h . | k . h . s . k k | k . h . s . . .'},
      dungeon: {bpm: 92, lead: 'A4 - - C5 - - E5 - | F5 - - E5 - - C5 - | D5 - - F5 - - A5 - | G#5 - - - E5 - - - | A5 - - G5 - - E5 - | F5 - - E5 - - D5 - | D5 - F5 - E5 - G#4 - | A4 - - - - - . .',
        harm: 'A3 . E4 . A3 . E4 . | F3 . C4 . F3 . C4 . | D3 . A3 . D3 . A3 . | E3 . B3 . E3 . G#3 . | A3 . E4 . A3 . E4 . | F3 . C4 . F3 . C4 . | D3 . A3 . E3 . B3 . | A3 . E4 . A3 . . .',
        bass: 'A2 - - - E3 - - - | F2 - - - C3 - - - | D2 - - - A2 - - - | E2 - - - B2 - - - | A2 - - - E3 - - - | F2 - - - C3 - - - | D2 - - - E2 - - - | A2 - - - - - . .',
        drum: 'k . . . . . h . | k . . . . . h . | k . . . . . h . | k . . . s . h . | k . . . . . h . | k . . . . . h . | k . . . s . h . | k . . . . . . .'},
      battle: {bpm: 152, lead: 'D5 - F5 - A5 - D6 - | C6 Bb5 A5 - F5 - D5 - | E5 - G5 - C6 - E6 - | C#6 - - - A5 - E5 - | F5 - A5 - D6 - F6 E6 | D6 - Bb5 - F5 - D5 F5 | G5 - Bb5 - A5 - C#6 - | D6 - - - D5 . D5 .',
        harm: 'D4 F4 A4 F4 D4 F4 A4 F4 | Bb3 D4 F4 D4 Bb3 D4 F4 D4 | C4 E4 G4 E4 C4 E4 G4 E4 | A3 C#4 E4 C#4 A3 C#4 E4 C#4 | D4 F4 A4 F4 D4 F4 A4 F4 | Bb3 D4 F4 D4 Bb3 D4 F4 D4 | G3 Bb3 D4 Bb3 A3 C#4 E4 C#4 | D4 F4 A4 F4 D4 . D4 .',
        bass: 'D2 D3 D2 D3 D2 D3 D2 D3 | Bb1 Bb2 Bb1 Bb2 Bb1 Bb2 Bb1 Bb2 | C2 C3 C2 C3 C2 C3 C2 C3 | A1 A2 A1 A2 A1 A2 A1 A2 | D2 D3 D2 D3 D2 D3 D2 D3 | Bb1 Bb2 Bb1 Bb2 Bb1 Bb2 Bb1 Bb2 | G1 G2 G1 G2 A1 A2 A1 A2 | D2 D3 D2 D3 D2 . D2 .',
        drum: 'k h s h k k s h | k h s h k k s h | k h s h k k s h | k h s h k s s s | k h s h k k s h | k h s h k k s h | k h s h k k s h | k . s . k . s .'},
      boss: {bpm: 164, lead: 'E5 - G5 - B5 - E6 - | C6 - B5 - G5 - E5 - | F#5 - A5 - D6 - C6 B5 | D#6 - - - B5 - F#5 - | E6 - D6 - B5 - G5 B5 | C6 - G5 - E5 - G5 - | A5 - C6 - B5 - D#6 - | E6 - - - E5 E5 E5 .',
        harm: 'E4 B4 E4 B4 E4 B4 E4 B4 | C4 G4 C4 G4 C4 G4 C4 G4 | D4 A4 D4 A4 D4 A4 D4 A4 | B3 F#4 B3 F#4 B3 D#4 B3 F#4 | E4 B4 E4 B4 E4 B4 E4 B4 | C4 G4 C4 G4 C4 G4 C4 G4 | A3 E4 A3 E4 B3 F#4 B3 F#4 | E4 B4 E4 B4 E4 . E4 .',
        bass: 'E2 E3 E2 E3 E2 E3 G2 E2 | C2 C3 C2 C3 C2 C3 E2 C2 | D2 D3 D2 D3 D2 D3 F#2 D2 | B1 B2 B1 B2 B1 B2 D#2 B1 | E2 E3 E2 E3 E2 E3 G2 E2 | C2 C3 C2 C3 C2 C3 E2 C2 | A1 A2 A1 A2 B1 B2 B1 B2 | E2 E3 E2 E3 E2 . E2 .',
        drum: 'k h s h k h s s | k h s h k h s h | k h s h k h s s | k h s k k s s s | k h s h k h s s | k h s h k h s h | k h s h k h s s | k k s . k k s .'},
      win: {bpm: 150, loop: false, lead: 'C5 E5 G5 C6 - G5 C6 - | E6 - - - - - . .', harm: 'E4 G4 C5 E5 - C5 E5 - | G5 - - - - - . .', bass: 'C3 . G2 . C3 . G2 . | C3 - - - - - . .', drum: 'k . s . k . s . | k . . . . . . .'}
    };
    for(const k in T) ['lead', 'harm', 'bass', 'drum'].forEach(ch => { if(T[k][ch]) T[k][ch] = parse(T[k][ch]); });
    const waves = {};
    function pulse(c, duty){
      if(waves[duty] && waves[duty].c === c) return waves[duty].w;
      const n = 48, re = new Float32Array(n), im = new Float32Array(n);
      for(let i = 1; i < n; i++) re[i] = 2 / (i * Math.PI) * Math.sin(i * Math.PI * duty);
      const w = c.createPeriodicWave(re, im); waves[duty] = {c, w}; return w;
    }
    let bus = null, busC = null;
    function getBus(c){
      if(bus && busC === c) return bus;
      busC = c; bus = c.createGain(); bus.gain.value = 0;
      const lp = c.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 5200;
      bus.connect(lp); out(lp, .18);
      return bus;
    }
    function note(c, f, t, d, kind){
      const o = c.createOscillator(), g = c.createGain();
      if(kind === 'bass') o.type = 'triangle'; else o.setPeriodicWave(pulse(c, kind === 'lead' ? .25 : .5));
      o.frequency.setValueAtTime(f, t);
      if(kind === 'lead' && d > .3){ const l = c.createOscillator(), lg = c.createGain(); l.frequency.value = 5.5; lg.gain.setValueAtTime(0, t); lg.gain.linearRampToValueAtTime(f * .012, t + d); l.connect(lg); lg.connect(o.frequency); l.start(t); l.stop(t + d + .05); }
      const v = kind === 'lead' ? .075 : kind === 'harm' ? .032 : .16;
      g.gain.setValueAtTime(.0001, t); g.gain.exponentialRampToValueAtTime(v, t + .006);
      g.gain.setValueAtTime(v * (kind === 'bass' ? 1 : .7), t + Math.min(.08, d * .5)); g.gain.exponentialRampToValueAtTime(.0001, t + d);
      o.connect(g); g.connect(getBus(c)); o.start(t); o.stop(t + d + .02);
    }
    function drum(c, k, t){
      const b = getBus(c);
      if(k === 'k'){ const o = c.createOscillator(), g = c.createGain(); o.frequency.setValueAtTime(160, t); o.frequency.exponentialRampToValueAtTime(40, t + .12); g.gain.setValueAtTime(.32, t); g.gain.exponentialRampToValueAtTime(.0001, t + .14); o.connect(g); g.connect(b); o.start(t); o.stop(t + .16); return; }
      const s = c.createBufferSource(); s.buffer = noiseBuf; s.loop = true;
      const fl = c.createBiquadFilter(), g = c.createGain();
      fl.type = k === 'h' ? 'highpass' : 'bandpass'; fl.frequency.value = k === 'h' ? 7000 : 1700; fl.Q.value = k === 'h' ? .7 : .9;
      const d = k === 'h' ? .035 : .11, v = k === 'h' ? .05 : .13;
      g.gain.setValueAtTime(v, t); g.gain.exponentialRampToValueAtTime(.0001, t + d);
      s.connect(fl); fl.connect(g); g.connect(b); s.start(t, Math.random() * .5); s.stop(t + d + .02);
    }
    let cur = null, curName = '', back = '', step = 0, nextT = 0, timer = 0;
    function schedule(){
      if(!cur || !enabled || !on) return;
      const c = ac && ac.state === 'running' && !stale ? ac : null;
      if(!c){ nextT = 0; return; }
      const b = getBus(c);
      if(b.gain.value < .9){ b.gain.cancelScheduledValues(NOW); b.gain.setValueAtTime(b.gain.value, NOW); b.gain.linearRampToValueAtTime(1, NOW + .4); }
      const sd = 60 / cur.bpm / 2;
      if(!nextT || nextT < NOW) nextT = NOW + .05;
      const len = cur.lead.len;
      while(nextT < NOW + .3){
        ['lead', 'harm', 'bass'].forEach(ch => { const tr = cur[ch]; if(!tr) return; tr.ev.forEach(e => { if(e.at === step){ const f = freq(e.n); if(f) note(c, f, nextT, (e.end - e.at) * sd * .95, ch); } }); });
        if(cur.drum) cur.drum.ev.forEach(e => { if(e.at === step) drum(c, e.n, nextT); });
        nextT += sd; step++;
        if(step >= len){
          step = 0;
          if(cur.loop === false){ const r = back; cur = null; curName = ''; setTimeout(() => play(r), Math.max(0, (nextT - NOW) * 1000)); return; }
        }
      }
    }
    function fadeOut(){ if(bus && busC){ try { bus.gain.cancelScheduledValues(busC.currentTime); bus.gain.setValueAtTime(bus.gain.value, busC.currentTime); bus.gain.linearRampToValueAtTime(0, busC.currentTime + .25); } catch(e){} } }
    function play(n){
      if(n === curName && cur) return;
      // a jingle always finishes; what comes next waits for it
      if(curName === 'win' && cur && n){ back = n; return; }
      fadeOut();
      // a fresh bus, so notes already queued for the old tune fade away with it
      bus = null;
      cur = n && T[n] ? T[n] : null; curName = cur ? n : ''; step = 0; nextT = 0;
      if(cur && !timer) timer = setInterval(schedule, 60);
      if(!cur && timer){ clearInterval(timer); timer = 0; }
      schedule();
    }
    function jingle(n){ const r = curName; back = r; fadeOut(); bus = null; cur = T[n]; curName = n; step = 0; nextT = 0; if(!timer) timer = setInterval(schedule, 60); schedule(); }
    return {play, jingle, get enabled(){ return enabled; }, setEnabled(v){ enabled = v; try { localStorage.setItem(MKEY, v ? 'on' : 'off'); } catch(e){} if(!v) fadeOut(); else { bus = null; nextT = 0; } }};
  })();
  const api = {
    get on(){ return on; },
    set(v){ on = v; if(v) stale = true; try { localStorage.setItem(KEY, v ? 'on' : 'off'); } catch(e){} if(!v && ac){ try { ac.suspend(); } catch(e){} } },
    unlock(){ ctx(); },
    // called on every real tap / key press: marks the moment iOS allows audio, then wakes the engine
    gesture(){ gestureAt = performance.now(); ctx(); },
    // soft keyboard "thock": tiny filtered tap + low body
    tick(){ noise({f: jit(3400, .12), q: .9, d: .014, vol: .09, wet: .3}); tone({f: jit(210, .06), f1: 130, d: .045, vol: .16, wet: .2}); },
    // water-drop bubble "bloop"
    pop(){ const r = jit(1, .07); tone({f: 360*r, f1: 1150*r, glide: .035, d: .075, vol: .3}); noise({ft:'highpass', f: 6000, d: .006, vol: .05, wet: 0}); },
    // glassy marimba note
    bell(f, t, vol){ const v = vol || .17; tone({f, t, d: .38, vol: v}); tone({f: f*2, t, d: .16, vol: v*.32}); tone({f: f*4.02, t, d: .05, vol: v*.22, wet: .4}); },
    // completing a cell: bloop + a note that climbs with the day's count
    done(n){ api.pop(); const i = Math.max(0, Math.min(PENTA.length - 1, (n || 1) - 1)); api.bell(PENTA[i], .05); },
    undo(){ tone({f: jit(560, .03), f1: 290, glide: .1, d: .14, vol: .18}); api.tick(); },
    // mochi squish + springy "pyon"
    squish(){ noise({f: 380, f1: 1900, q: 4, a: .01, d: .11, vol: .12, wet: .2}); tone({f: jit(260, .05), f1: 700, glide: .09, d: .17, vol: .2, vib: 22}); },
    // tiny creature voice
    chirp(kind){
      const pats = kind === 'q'
        ? [[820, 1050, .06, 0], [1000, 1600, .09, .1]]
        : [[pick([880,940,990]), 1400, .055, 0], [pick([1050,1120]), 1650, .06, .085], [pick([1250,1320]), 1900, .05, .17]].slice(0, pick([2,3]));
      pats.forEach(p => tone({type:'triangle', f: p[0], f1: p[1], glide: p[2]*.8, d: p[2], t: p[3], vol: .14, lp: 3200}));
    },
    // pet "talking": soft syllable blips, one per few letters
    babble(text, delay){
      const n = Math.max(3, Math.min(11, Math.round((text || '').length / 7)));
      const sc = [660,740,830,880,990,1110,1245];
      const dark = typeof CHAR !== 'undefined' && CHAR === 'chika';   // Chika's voice: lower and rounder
      let t = delay || 0;
      for(let i = 0; i < n; i++){
        const f = pick(sc) * (i === n - 1 ? 1.12 : 1) * (dark ? .72 : 1);
        tone({type: dark ? 'triangle' : 'square', f, f1: f * (Math.random() < .5 ? 1.08 : .93), glide: .045, a: .006, d: .05, t, vol: dark ? .085 : .045, lp: dark ? 1500 : 1700, wet: .25});
        t += .062 + Math.random() * .02;
      }
    },
    sparkle(t0, count){ for(let i = 0; i < (count || 8); i++) tone({f: 2200 + Math.random()*2600, t: (t0 || 0) + Math.random()*.9, d: .09, vol: .045, wet: .8}); },
    evolve(){
      [0,2,4,5,7,9,10].forEach((ix, i) => api.bell(PENTA[ix], i*.075, .14));
      api.sparkle(.1, 12);
      [523.25,659.25,783.99].forEach(f => tone({type:'triangle', f, t: .62, a: .03, d: 1.1, vol: .07, wet: .7}));
    },
    fanfare(){ [0,2,3,5].forEach((ix, i) => api.bell(PENTA[ix + 2], .1 + i*.09, .16)); api.sparkle(.4, 8); },
    // a big moment: three paper poppers, a bright run up and a ringing chord under a shower of sparkles
    confetti(){
      [0, .11, .23].forEach((t, i) => {
        tone({f: jit(170 - i * 14, .04), f1: 55, glide: .13, d: .17, vol: .3, t, wet: .12});
        noise({ft: 'bandpass', f: 1400, f1: 6200, q: .55, a: .003, d: .2, vol: .2, t, wet: .35});
      });
      [0,1,2,3,4,5,6,7].forEach((ix, i) => api.bell(PENTA[ix + 1], .3 + i * .055, .12));
      [5, 7, 10].forEach((ix, i) => api.bell(PENTA[ix], .78 + i * .012, .15 - i * .02));
      api.sparkle(.32, 16); api.sparkle(1.1, 10);
    },
    newCell(){ api.pop(); [2,4,7].forEach((ix, i) => api.bell(PENTA[ix], .06 + i*.08, .13)); },
    // paper page turning: airy sweep + soft landing
    page(){ noise({f: 700, f1: 2600, q: .7, a: .04, d: .2, vol: .15, wet: .35}); noise({ft:'highpass', f: 4500, t: .06, a: .01, d: .09, vol: .045, wet: .2}); tone({f: 95, f1: 70, t: .03, d: .07, vol: .09, wet: .1}); },
    // tiny pencil scratch while writing
    pencil(){ const n = performance.now(); if(n - lastPencil < 45) return; lastPencil = n; noise({f: jit(5200, .25), q: 2.2, a: .002, d: jit(.018, .3), vol: .028, wet: .08}); },
    // toy-button beep, like the real thing but softer
    beep(){ tone({type:'square', f: 2350, a: .002, d: .035, vol: .035, lp: 4200, wet: .05}); },
    // crunchy little bites
    chomp(n){ for(let i = 0; i < (n || 3); i++){ const t = .05 + i * .3; noise({f: jit(1400, .2), q: 1.2, t, a: .002, d: .05, vol: .16, wet: .15}); noise({f: jit(3200, .2), q: 2, t: t + .02, d: .03, vol: .07, wet: .1}); tone({f: jit(190, .1), f1: 120, t, d: .07, vol: .12, wet: .1}); } },
    // water swirl when cleaning up
    flush(){ noise({f: 300, f1: 2600, q: .8, a: .08, d: .55, vol: .16, wet: .5}); for(let i = 0; i < 6; i++) tone({f: jit(500 + i * 120, .1), f1: jit(1100 + i * 150, .1), glide: .04, t: .1 + i * .07, d: .06, vol: .07, wet: .4}); },
    // medicine: a rising, sparkly "all better"
    shot(){ tone({type:'triangle', f: 700, f1: 1700, glide: .25, d: .28, vol: .12, wet: .4}); api.sparkle(.25, 6); },
    // telling off: two low buzzes
    scold(){ [0, .16].forEach(t => tone({type:'square', f: 196, f1: 175, t, d: .1, vol: .06, lp: 900, wet: .1})); },
    // "mm-mm", no thanks
    nope(){ tone({type:'triangle', f: 520, f1: 440, d: .09, vol: .12, lp: 2400}); tone({type:'triangle', f: 440, f1: 360, t: .14, d: .12, vol: .12, lp: 2400}); },
    coin(){ api.bell(1318.51, 0, .15); api.bell(1975.53, .08, .15); api.sparkle(.12, 5); },
    lose(){ [659.25, 523.25, 440].forEach((f, i) => tone({type:'triangle', f, t: i * .14, d: .16, vol: .1, lp: 2600, wet: .3})); },
    // PuchiQuest: battle sounds, chiptune-ish (square waves through a soft filter)
    qstart(){ [261.63, 329.63, 392, 523.25].forEach((f, i) => tone({type:'square', f, t: i * .07, d: .09, vol: .05, lp: 2400, wet: .2})); noise({f: 1800, f1: 400, q: .7, t: .3, a: .01, d: .25, vol: .08, wet: .4}); },
    qhit(){ noise({f: jit(1100, .15), f1: 260, q: 1, a: .002, d: .09, vol: .22, wet: .15}); tone({type:'square', f: jit(240, .08), f1: 100, d: .09, vol: .07, lp: 1500, wet: .1}); },
    qcrit(){ api.qhit(); tone({type:'square', f: 880, f1: 1760, t: .05, d: .13, vol: .06, lp: 3200, wet: .2}); api.sparkle(.08, 4); },
    qouch(){ tone({type:'triangle', f: jit(520, .05), f1: 300, d: .12, vol: .14, lp: 2200}); noise({f: 700, q: 1.2, d: .06, vol: .1, wet: .1}); },
    qmiss(){ noise({f: 2400, f1: 5200, q: .9, a: .01, d: .12, vol: .07, wet: .3}); },
    qheal(){ [783.99, 987.77, 1174.66].forEach((f, i) => api.bell(f, i * .07, .1)); api.sparkle(.15, 5); },
    qsleep(){ [659.25, 523.25, 392, 329.63].forEach((f, i) => tone({type:'sine', f, t: i * .16, d: .22, vol: .1, wet: .5})); },
    qpoof(){ noise({f: 1500, f1: 160, q: .8, a: .01, d: .32, vol: .16, wet: .4}); tone({type:'square', f: 330, f1: 80, d: .25, vol: .05, lp: 1200}); },
    qwin(){ [523.25, 659.25, 783.99, 1046.5, 783.99, 1046.5].forEach((f, i) => tone({type:'square', f, t: i * .1, d: i === 5 ? .42 : .09, vol: .06, lp: 3000, wet: .25})); api.sparkle(.6, 6); },
    qlevel(){ [523.25, 659.25, 783.99, 1046.5, 1318.51].forEach((f, i) => api.bell(f, i * .07, .12)); api.sparkle(.35, 8); },
    lightOff(){ [1046.5, 783.99, 523.25].forEach((f, i) => api.bell(f, i * .12, .12)); },
    lightOn(){ [523.25, 783.99, 1046.5].forEach((f, i) => api.bell(f, i * .09, .12)); },
    // is the engine up right now, without needing a tap?
    ready(){ return on && !!ac && !stale && ac.state === 'running'; },
    // background music for the console games: a tiny chiptune sequencer (two pulse waves, a triangle bass and drums)
    // music('field') loops a track, music(null) stops; jingle('win') plays once and then goes back to the loop
    music(n){ Music.play(n); },
    jingle(n){ Music.jingle(n); },
    get musicOn(){ return Music.enabled; },
    setMusic(v){ Music.setEnabled(v); },
    // A short, sweet tune made up on the spot: major pentatonic, a phrase that climbs and an answer
    // that comes home to the tonic, sung by a soft ocarina-like voice over music-box plucks.
    // Returns its length in seconds (0 if no sound).
    melody(){
      
      const root = MELODY_ROOT || pick([523.25, 554.37, 587.33, 622.25, 659.25]);
      const STEPS = [0, 2, 4, 7, 9, 12, 14, 16];
      const fq = i => root * Math.pow(2, STEPS[Math.max(0, Math.min(STEPS.length - 1, i))] / 12);
      const beat = 60 / rand(108, 138);
      const RH = [[1, 1, 1, 1], [.5, .5, 1, .5, .5, 1], [1, .5, .5, 1, 1], [.75, .25, .5, .5, 2], [.5, .5, .5, .5, 1, 1]];
      const clamp = d => Math.max(0, Math.min(6, d));
      const notes = [];
      let deg = pick([0, 2, 4]);
      const a = pick(RH), b = pick(RH);
      a.forEach((d, i) => { notes.push([deg, d]); deg = clamp(deg + pick(i < a.length / 2 ? [1, 1, 2, -1] : [1, -1, 2, 0])); });
      b.forEach((d, i) => { const last = i === b.length - 1; notes.push([last ? pick([0, 0, 5]) : deg, last ? Math.max(d, 1) : d]); deg = clamp(deg + pick([-1, -1, -2, 1, 0])); });
      let t = .06;
      notes.forEach(([g, d], i) => {
        const dur = d * beat;
        voice(fq(g), t, dur * .9);
        if(i % 2 === 0) api.bell(fq(g) / 2, t, .045);
        t += dur;
      });
      api.bell(root / 2, t, .05); api.bell(root, t + .02, .04);
      api.sparkle(t - .05, 4);
      return t + .5;
    }
  };
  // the singing voice: a little scoop into each note, then a gentle vibrato
  function voice(f, t0, d){
    const c = ac; if(!c) return;
    const t = NOW + .006 + t0, vol = .11;
    const o = c.createOscillator(); o.type = 'triangle';
    o.frequency.setValueAtTime(f * .985, t); o.frequency.exponentialRampToValueAtTime(f, t + .05);
    const lfo = c.createOscillator(), lg = c.createGain(); lfo.frequency.value = 5.3;
    lg.gain.setValueAtTime(0, t); lg.gain.linearRampToValueAtTime(f * .009, t + Math.min(.28, d * .7));
    lfo.connect(lg); lg.connect(o.frequency);
    const o2 = c.createOscillator(); o2.type = 'sine'; o2.frequency.value = f * 2;
    const g2 = c.createGain(); g2.gain.value = .16; o2.connect(g2);
    const fl = c.createBiquadFilter(); fl.type = 'lowpass'; fl.frequency.value = 2600; fl.Q.value = .5;
    const g = c.createGain();
    g.gain.setValueAtTime(.0001, t); g.gain.exponentialRampToValueAtTime(vol, t + .035);
    g.gain.setValueAtTime(vol, t + Math.max(.04, d - .09)); g.gain.exponentialRampToValueAtTime(.0001, t + d + .07);
    o.connect(fl); g2.connect(fl); fl.connect(g); out(g, .55);
    [o, o2, lfo].forEach(x => { x.start(t); x.stop(t + d + .12); });
  }
  api.tone = tone; api.noise = noise; api.out = out; api.noiseBuf = noiseBuf;
  return api;
})();
